### ISSUE TITLE
Drop the releases branch

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore-build#14]
I think there's no actual reason why it needs to be there.

We could have a tag/branch called "current" to signify what's the latest release, but the current schema of "having a branch with merge commits between the last build commit (the ones with the binaries) and the current master be the next release commit" I feel that has no use case or reason to be kept.

**Comment by yemel** [comment]
Related: https://github.com/bitpay/bitcore/issues/986

**Comment by maraoz** [comment]
I don't see the need for a special branch for this. That's what tags are for. I vote for removing `releases`
