### ISSUE TITLE
uglify mangles object names that bitcore requires

### ISSUE THREAD

**Issue by johnkozan** [bitpay/bitcore-build#3]
I'm using bitcore 0.8.5 from bower.

Using the minified brower bundle, several bitcore functions fail because they expect arguments to be of a certain type, which uglify has mangled to a single letter name.

For example
https://github.com/bitpay/bitcore/blob/master/lib/address.js#L231

``` javascript
  if (!(pubkey instanceof PublicKey)) {
    throw new TypeError('Address must be an instance of PublicKey.');
  }
```

but `PublicKey` has been mangled to a single letter and I get the following error:

```
 TypeError: Address must be an instance of PublicKey.
    at Function.n._transformPublicKey (http://localhost:9000/bower_components/bitcore/browser/bitcore.min.js:1:5708)
    at Function.n.fromPublicKey (http://localhost:9000/bower_components/bitcore/browser/bitcore.min.js:1:6453)
    at l.d.toAddress (http://localhost:9000/bower_components/bitcore/browser/bitcore.min.js:4:4457)
```

**Comment by maraoz** [comment]
thanks for reporting. We'll check this and report back

**Comment by maraoz** [comment]
just for the record, what browser are you using? 
We fixed some related IE stuff on v0.8.6

**Comment by johnkozan** [comment]
I updated my bower.json to bitcore 0.8.6 and the issue seems to have been resolved.

Tested on Chrome and Firefox on Linux.

**Comment by maraoz** [comment]
that's awesome to know!
